-- Seed Noctis Gallery records with local staged image paths.
-- These URLs can later be replaced with Supabase Storage public URLs from the
-- gallery-records bucket.

insert into public.gallery_records (
  title,
  slug,
  description,
  lore_note,
  record_type,
  origin,
  status,
  full_image_url,
  preview_image_url,
  required_fragments,
  is_fragmented,
  is_featured,
  is_active,
  sort_order,
  tags,
  themes,
  related_room
) values
  (
    'The Candlelit Witness',
    'the-candlelit-witness',
    'A portrait recovered from a room where the candles were still warm.',
    'The face appears only when the flame leans toward the glass.',
    'portrait',
    'Noctis Archive',
    'available',
    '/assets/noctis/gallery/portraits/madame_lucaria.png',
    '/assets/noctis/gallery/portraits/madame_lucaria.png',
    0,
    false,
    false,
    true,
    10,
    array['Portraits', 'Noctis', 'Blood Moon'],
    array['portrait', 'candlelight', 'witness'],
    'The Gallery'
  ),
  (
    'The Red Shore Beneath Noctis',
    'the-red-shore-beneath-noctis',
    'A ruined coast under a blood-red moon, cataloged before the tide erased the stones.',
    'The moon returns to the shore that forgot its own name.',
    'place',
    'Noctis Archive',
    'available',
    '/assets/noctis/gallery/places/blood-red-moon-over-haunted-ruins.png',
    '/assets/noctis/gallery/places/blood-red-moon-over-haunted-ruins.png',
    0,
    false,
    true,
    true,
    20,
    array['Places', 'Blood Moon', 'Noctis'],
    array['shore', 'ruins', 'blood moon'],
    'The Gallery'
  ),
  (
    'The Astrolabe of Noctis',
    'the-astrolabe-of-noctis',
    'An instrument of brass and shadow, recovered from a study that tracked impossible stars.',
    'Every ring points home, but never to the same home twice.',
    'symbol',
    'Noctis Archive',
    'recovered',
    '/assets/noctis/gallery/symbols/astrolabe-in-a-gothic-study.png',
    '/assets/noctis/gallery/symbols/astrolabe-in-a-gothic-study.png',
    0,
    false,
    false,
    true,
    30,
    array['Symbols', 'Archive', 'Noctis'],
    array['astrolabe', 'study', 'stars'],
    'The Gallery'
  ),
  (
    'The Path That Refused the Sun',
    'the-path-that-refused-the-sun',
    'A moonlit forest path that resists daylight in every recovered exposure.',
    'No dawn has crossed this threshold and remained intact.',
    'place',
    'Noctis Archive',
    'available',
    '/assets/noctis/gallery/places/misty-moonlit-forest-path.png',
    '/assets/noctis/gallery/places/misty-moonlit-forest-path.png',
    0,
    false,
    false,
    true,
    40,
    array['Places', 'Forest', 'Noctis'],
    array['forest', 'moonlight', 'path'],
    'The Gallery'
  ),
  (
    'The Ruins of Low Tide',
    'the-ruins-of-low-tide',
    'Sea-battered gothic ruins revealed only when the storm pulls the water away.',
    'The stones remember each tide as a warning.',
    'place',
    'Noctis Archive',
    'available',
    '/assets/noctis/gallery/places/gothic-ruins-by-the-stormy-sea.png',
    '/assets/noctis/gallery/places/gothic-ruins-by-the-stormy-sea.png',
    0,
    false,
    false,
    true,
    50,
    array['Places', 'Ruins', 'Water'],
    array['sea', 'storm', 'ruins'],
    'The Gallery'
  ),
  (
    'The Figure Beneath the Moon',
    'the-figure-beneath-the-moon',
    'A solitary watcher appears beneath a moon that does not match any recorded sky.',
    'It is unclear whether the figure is waiting, guarding, or being watched.',
    'anomaly',
    'Noctis Archive',
    'unknown',
    '/assets/noctis/gallery/anomalies/moonlit-figure-in-a-haunted-landscape.png',
    '/assets/noctis/gallery/anomalies/moonlit-figure-in-a-haunted-landscape.png',
    0,
    false,
    false,
    true,
    60,
    array['Anomalies', 'Watchers', 'Veil'],
    array['moon', 'watcher', 'haunted landscape'],
    'The Gallery'
  ),
  (
    'The Alchemist''s Last Table',
    'the-alchemists-last-table',
    'A recovered laboratory table left arranged as if its owner intended to return before morning.',
    'The final mixture still throws a blue shadow.',
    'recovered',
    'Noctis Archive',
    'recovered',
    '/assets/noctis/gallery/recovered/gothic-alchemist-s-candlelit-laboratory.png',
    '/assets/noctis/gallery/recovered/gothic-alchemist-s-candlelit-laboratory.png',
    0,
    false,
    false,
    true,
    70,
    array['Recovered', 'Objects', 'Archive'],
    array['alchemy', 'laboratory', 'candlelight'],
    'The Gallery'
  ),
  (
    'The Bound Star Index',
    'the-bound-star-index',
    'A grimoire of star marks, sealed with a clasp that opens only under red light.',
    'The pages do not describe constellations. They remember them.',
    'symbol',
    'Noctis Archive',
    'recovered',
    '/assets/noctis/gallery/recovered/gothic-occult-grimoire-in-candlelight.png',
    '/assets/noctis/gallery/recovered/gothic-occult-grimoire-in-candlelight.png',
    0,
    false,
    false,
    true,
    80,
    array['Symbols', 'Documents', 'Archive'],
    array['grimoire', 'index', 'stars'],
    'The Gallery'
  ),
  (
    'The Crown That Grew Backward',
    'the-crown-that-grew-backward',
    'A crowned figure whose adornment appears organic, thorned, and still growing.',
    'The crown did not descend onto the head. It climbed out of it.',
    'portrait',
    'Noctis Archive',
    'unknown',
    '/assets/noctis/gallery/portraits/ethereal-crown-of-organic-tendrils.png',
    '/assets/noctis/gallery/portraits/ethereal-crown-of-organic-tendrils.png',
    0,
    false,
    false,
    true,
    90,
    array['Portraits', 'Unknown Records', 'Noctis'],
    array['crown', 'organic', 'unknown'],
    'The Gallery'
  ),
  (
    'The Spiral Beyond the Veil',
    'the-spiral-beyond-the-veil',
    'A fiery spiral phenomenon recorded beyond the visible edge of the Veil.',
    'The image bends inward where the room should end.',
    'anomaly',
    'Noctis Archive',
    'available',
    '/assets/noctis/gallery/anomalies/cosmic-spiral-of-fiery-energy.png',
    '/assets/noctis/gallery/anomalies/cosmic-spiral-of-fiery-energy.png',
    0,
    false,
    false,
    true,
    100,
    array['Anomalies', 'The Veil', 'Astral'],
    array['spiral', 'fire', 'veil'],
    'The Gallery'
  ),
  (
    'Noctivar Keep',
    'noctivar-keep',
    'A crimson-sky fortress identified in older records as one of Noctis'' outer keeps.',
    'The keep is always seen from below, as though the image itself is kneeling.',
    'place',
    'Noctis Archive',
    'available',
    '/assets/noctis/gallery/places/noctis-castle.png',
    '/assets/noctis/gallery/places/noctis-castle.png',
    0,
    false,
    false,
    true,
    110,
    array['Places', 'Castle', 'Noctis'],
    array['castle', 'crimson sky', 'keep'],
    'The Gallery'
  ),
  (
    'The Road to Veilspire',
    'the-road-to-veilspire',
    'A lone rider approaches a distant gothic fortress under hostile moonlight.',
    'The road lengthens each time the record is viewed.',
    'place',
    'Noctis Archive',
    'available',
    '/assets/noctis/gallery/places/knight_percy.png',
    '/assets/noctis/gallery/places/knight_percy.png',
    0,
    false,
    false,
    true,
    120,
    array['Places', 'Knight', 'Veilspire'],
    array['road', 'knight', 'fortress'],
    'The Gallery'
  ),
  (
    'The Road Between Castles',
    'the-road-between-castles',
    'A cursed-land map connecting Noctis Castle and Veilspire Citadel through unmarked roads.',
    'The cartographer drew the warning first, then the path.',
    'map',
    'Noctis Archive',
    'recovered',
    '/assets/noctis/gallery/maps/map1.png',
    '/assets/noctis/gallery/maps/map1.png',
    0,
    false,
    false,
    true,
    130,
    array['Maps', 'Noctis Castle', 'Veilspire Citadel'],
    array['map', 'castle road', 'cursed lands'],
    'The Gallery'
  ),
  (
    'The Thorn-Crowned King',
    'the-thorn-crowned-king',
    'A recovered royal portrait from a throne room whose banners have been scratched from the image.',
    'The king is named only by what refuses to bow.',
    'portrait',
    'Noctis Archive',
    'recovered',
    '/assets/noctis/gallery/portraits/king_feranzo.png',
    '/assets/noctis/gallery/portraits/king_feranzo.png',
    0,
    false,
    false,
    true,
    140,
    array['Portraits', 'King', 'Noctis'],
    array['king', 'throne', 'crown'],
    'The Gallery'
  ),
  (
    'Veilspire Citadel',
    'veilspire-citadel',
    'A distant citadel fixed beneath a pale moon, indexed as a companion landmark to Noctivar Keep.',
    'The citadel appears closer in every copy, though the road never shortens.',
    'place',
    'Noctis Archive',
    'available',
    '/assets/noctis/gallery/places/veilspire-citadel.png',
    '/assets/noctis/gallery/places/veilspire-citadel.png',
    0,
    false,
    false,
    true,
    150,
    array['Places', 'Citadel', 'Veilspire'],
    array['citadel', 'moonlight', 'fortress'],
    'The Gallery'
  ),
  (
    'Alana Noctis',
    'alana-noctis',
    'A recovered portrait marked with a partial Noctis family name and no accompanying date.',
    'The eyes hold steady even when the frame is moved.',
    'portrait',
    'Noctis Archive',
    'available',
    '/assets/noctis/gallery/portraits/alana_noctis_a.png',
    '/assets/noctis/gallery/portraits/alana_noctis_a.png',
    0,
    false,
    false,
    true,
    160,
    array['Portraits', 'Noctis'],
    array['portrait', 'noctis family', 'recovered likeness'],
    'The Gallery'
  ),
  (
    'Alanah Noctis',
    'alanah-noctis',
    'A second Noctis portrait with a near-matching name, preserved in warmer shadow.',
    'The Archive records the spelling twice and refuses to choose.',
    'portrait',
    'Noctis Archive',
    'available',
    '/assets/noctis/gallery/portraits/alanah_noctis.png',
    '/assets/noctis/gallery/portraits/alanah_noctis.png',
    0,
    false,
    false,
    true,
    170,
    array['Portraits', 'Noctis'],
    array['portrait', 'noctis family', 'name variant'],
    'The Gallery'
  ),
  (
    'Veronica',
    'veronica',
    'A solitary portrait recovered without surname, chamber mark, or witness notation.',
    'Her name arrived before the image did.',
    'portrait',
    'Noctis Archive',
    'unknown',
    '/assets/noctis/gallery/portraits/veronica.png',
    '/assets/noctis/gallery/portraits/veronica.png',
    0,
    false,
    false,
    true,
    180,
    array['Portraits', 'Unknown Records', 'Noctis'],
    array['portrait', 'unknown', 'witness'],
    'The Gallery'
  )
on conflict (slug) do update
set
  title = excluded.title,
  description = excluded.description,
  lore_note = excluded.lore_note,
  record_type = excluded.record_type,
  origin = excluded.origin,
  status = excluded.status,
  full_image_url = excluded.full_image_url,
  preview_image_url = excluded.preview_image_url,
  required_fragments = excluded.required_fragments,
  is_fragmented = excluded.is_fragmented,
  is_featured = excluded.is_featured,
  is_active = excluded.is_active,
  sort_order = excluded.sort_order,
  tags = excluded.tags,
  themes = excluded.themes,
  related_room = excluded.related_room,
  updated_at = now();
